### ISSUE TITLE
Document how to set things up to run the benchmarks

### ISSUE THREAD

**Issue by treeowl** [haskell/containers#371] opened 2016-12-15 05:35 UTC
For dependency reasons, users must install certain packages manually in order to run the included benchmarks. We need to document this process, as discussed in #353.

**Comment by sjakobi** [comment] 2017-03-01 16:34
I currently use stack to run the benchmarks with e.g. `stack bench :intmap-benchmarks`. The workflow is pretty obnoxious though because after each edit of the benchmarks or library, 23 dependencies that depend on containers are rebuilt until finally the benchmarks are run.

To make this slightly more palatable it might make sense to move the benchmarks into a separate package.

My stack.yaml:

```
packages: ['.']
resolver: lts-8.3
```

**Comment by sjakobi** [comment] 2017-12-17 16:52
Once this is documented – and if the instructions also apply to the testsuites, I might be able to work on https://github.com/haskell/containers/issues/125 …

BTW there's a [duplicate of this issue](https://github.com/haskell/containers/issues/354).

**Closed** 2017-12-26 05:12 UTC
Labels: docs
