### ISSUE TITLE
Strictness of `foldr'` and `foldl'`

### ISSUE THREAD

**Issue by coot** [haskell/containers#749] opened 2020-10-07 07:29 UTC
To my surprise I found out that `foldr'` and `foldl'` are not as strict as I would think of.  They do not demand the result of every application of the accumulator function, instead they demand only when it is reaching the `Tip`. That's ok when folding to something like an `Int`, but let's look what happens when we fold to a list.

```
> import Data.Map (Map)
> import qualified Data.Map as Map
> x = Map.fromList $ (\x -> (x,x)) `map` [0..10] :: Map Int Int
> y = Map.foldr' (:) [] x :: [Int]
> y `seq` ()
()
> :sprint y
y = 0 : _
```
If the accumulator `:` was demanded after every application demanding `y` would force the spine of the list not just the first element.  And indeed [the implementation](https://hackage.haskell.org/package/containers-0.6.4.1/docs/src/Data.Map.Internal.html#foldr') reveals that this is indeed the case.

I also wrote a small [gist](https://gist.github.com/coot/4bda8ec91fbf5c22b3d521170d3b98dc) to play with this. It gives the following outpu for `Map.foldr'`, `Map.foldr` and then forcing the spine of the list with `length`, and a custom `foldr'` which demand every application of the accumulator:
```
*** Map.foldr' ***

"_ind (_bh (I# 1 : _thunk _fun (I# 2 : _thunk _fun (I# 4 : _thunk _fun ([] 5032544) (Bin (I# 8) (I# 8) (B
in (I# 6) (I# 6) (Bin (I# 5) (I# 5) (Tip 4457056) (Tip 4457056) 1) (Bin (I# 7) (I# 7) (Tip 4457056) (Tip 
4457056) 1) 3) (Bin (I# 9) (I# 9) (Tip 4457056) (Bin (I# 10) (I# 10) (Tip 4457056) (Tip 4457056) 1) 2) 6)
) (Bin (I# 3) (I# 3) (Tip 4457056) (Tip 4457056) 1)) (Tip 4457056)))"

*** Map.foldr' & seq ***

"_ind (_bh (I# 1 : _bh (I# 2 : _bh (I# 3 : _bh (I# 4 : _bh (I# 5 : _bh (I# 6 : _bh (I# 7 : _bh (I# 8 : _b
h (I# 9 : _bh (I# 10 : _bh ([] 5032544))))))))))))"

*** foldr' ***
"_ind (_bh (I# 1 : I# 2 : I# 3 : I# 4 : I# 5 : I# 6 : I# 7 : I# 8 : I# 9 : I# 10 : [] 5032544))"

```

As you can see `Map.foldr'` retains the original map, the other two don't.

The haddock of `foldr'` sais:

> Each application of the operator is evaluated before using the result in the next application.

I think that either the documentation should be more accurate about strictness of `foldr'` and `foldl'` (which is also affected in the same way), or the implementation should be amended. 

This was discovered when working on https://github.com/input-output-hk/ouroboros-network/pull/2631

**Comment by treeowl** [comment] 2020-10-07 07:38
They are always demanded, thanks to the left-to-right semantics of pattern matching. The bang in the first line forces the accumulator before the second pattern fails. Something else is going on here....

**Comment by coot** [comment] 2020-10-07 07:48
Another way to force the result in this case is to force the accumulator inside the accumulator function, i.e.
```
Map.foldr (\a !acc -> a : acc) []
```

**Comment by treeowl** [comment] 2020-10-07 07:54
Ah, I missed the gist before. Yes, the problem is the inner `go`. Let's fix that posthaste! Would you like to open a PR? I'd ask you to please use a bang pattern in your `let` binding rather than `seq` (just code style preference).

**Comment by coot** [comment] 2020-10-07 07:56
Yes, I will open a PR.

**Comment by treeowl** [comment] 2020-10-07 07:56
Thanks!

**Comment by treeowl** [comment] 2020-10-07 08:04
Actually, I think you can use `$!` here, right? Between `f` and its argument. Very compact.

**Comment by sjakobi** [comment] 2020-10-07 08:31
I think `fold{l,r}WithKey'` will need the same fix. The `IntMap` versions look good to me visually, but I didn't run any tests.

**Comment by coot** [comment] 2020-10-07 08:33
I checked  in `ghci` that `IntMap`'s `foldr'` and `foldl'` are strict.

**Comment by edsko** [comment] 2020-10-07 08:48
I'm not convinced that this is a bug in `Data.Map`: `foldr'` _is_ forcing the accumulator, like David said [above](https://github.com/haskell/containers/issues/749#issuecomment-704755547). You are passing a lazy function to a function that updates its accumulator strictly; it feels to me that `foldr'` is doing the right thing, but your accumulator update function is not. I would expect a strict fold function to update its accumulator strictly, not necessarily force the arguments _to_ the update function before calling it. But admittedly that is a bit of a gray area!

**Comment by treeowl** [comment] 2020-10-07 09:04
@edsko, I'm pretty sure the current behavior depends on the way the tree is balanced, which is really bad.

**Comment by edsko** [comment] 2020-10-07 10:52
But on the other hand, if you change this, you take away the user's control over what should and should not be forced. Admittedly, that would be a pretty obscure use case, so I'm not arguing that the "fix" is _wrong_, but it's not obviously _right_ to me either.

**Comment by treeowl** [comment] 2020-10-07 14:44
@edsko, the user can't predict the tree shape, so that "control" seems illusory.

**Comment by sjakobi** [comment] 2021-03-14 14:21
Given that the documentation for `foldr'` and `foldl'` says

> Each application of the operator is evaluated before using the result in the next application. 

I do think this is a bug that should be fixed.

It would be nice if we could achieve that in time for the next release and/or GHC 9.2.

@treeowl Have you taken a look at @coot's PR (#750)?

@coot Are you available to finish the fix, which should ideally include regression tests?

**Comment by coot** [comment] 2021-03-14 14:23
@sjakobi yes, if there's consensus to fix it I can add regressions tests.

**Comment by treeowl** [comment] 2021-03-15 02:00
@coot, yes, this is a bug that should be fixed. We currently use `chasing-bottoms` for strictness checking. Is that sufficient for your needs?

**Comment by coot** [comment] 2021-03-15 12:00
@treeowl I am not sure how to test this with `ChasingBottoms` package, but with [nothunks](https://hackage.haskell.org/package/nothunks-0.1.2/docs/NoThunks-Class.html#v:noThunks) this is quite easy:
```
pStrictFold :: Map Int Int -> IO Bool
pStrictFold !m = noThunks [] (foldr' (:) [] m >>= pure isNothing
```

**Closed** 2021-06-28 07:56 UTC
Labels: Map, bug, high-priority, urgent
