### ISSUE TITLE
Improve the running time of IntSet.size

### ISSUE THREAD

**Issue by kenta2** [haskell/containers#152] opened 2015-04-28 19:19 UTC
It would be nice the the running time of IntSet.size were O(1), instead of the O(n) that it is now.  This could be accomplished by making the size a part of the data structure, then tracking how the size changes on modifying operations.

**Comment by foxik** [comment] 2015-04-28 19:50
The question is how will the size tracking affect the time complexity of various operations. If we ever want to implement this, we have to benchmark the alternative representation and decide.

For `Set` and `Map`, the subtree sizes are required in order to keep the trees balanced, and the constant-time `size` is a nice side-effect. For `Int{Set,Map}` the subtree sizes are not required, and I assume the implementors did not want to pay the subtree size updating costs.

**Comment by kenta2** [comment] 2015-04-28 19:59
I strongly suspect the asymptotic time complexity, i.e., "big O", of the various operations will not change by adding size tracking, though there will be a change to constant factors hidden within the big O which will show up on benchmarks.  Ultimately, there will need to be a command decision about whether an asymptotic time complexity decrease in `size` is worth constant time factors increase in other operations.

I currently have an application which calls `size` repeatedly on large `IntSet`s , so this is killing me.

**Comment by tibbe** [comment] 2015-04-28 20:27
We need the benchmark numbers of the constant factor slowdown on the existing operations from storing the size. There's also the question of code complexity (I've tried to implement this for `HashMap` once and it adds some complexity.)

**Comment by foxik** [comment] 2015-04-28 20:53
There is no problem with the command decision -- the problem is with the patch introducing the subtree size updates :-)

If you need lot of `size`s, you can use `Set Int` -- it has very similar asymptotic complexity as `IntSet`, as the depth of a `Set Int` is always less than ~2.7 times the depth of `IntSet`.

It is unlikely that me or tibbe will work on the patch ourselves -- it will be quite a lot of work with uncertain result. But you are welcome to work on it yourself if you are interested ;-)

**Comment by treeowl** [comment] 2016-05-17 21:53
This might be fairly easy for simple operations, but unions, intersections, and differences seem to pose serious challenges. If you store the size only at the root, then you will have to count nodes in subtrees before you can discard them. If you store the size in each node, that will increase the size of the structure by one word per node. That seems likely more than users will want to pay if they're not using the feature. I'm going to close this for now. Perhaps we could eventually add a `SizedIntMap` module, but as Milan and Johan have indicated, it would be a lot of work.

**Closed by treeowl** 2016-05-17 21:53 UTC
Labels: low-priority
