### ISSUE TITLE
Chunking sequences

### ISSUE THREAD

**Issue by treeowl** [haskell/containers#144] opened 2015-03-15 03:55 UTC
Thinking about median-of-medians led me to think about a sort of reverse-`<*>`: `Data.List.Split.chunksOf :: Int -> [a] -> [[a]]`. And I think we can probably do something reasonably nice with it, in the `O(log^2 i)` incremental access realm. I don't have a full plan yet, but here's the beginning of the idea:

1. Given that we want to break up a sequence `xs` of length `n` into chunks of length `c` (assuming, for now, that it divides evenly), we can start by forming the sequence
```haskell
template=cycleN (n `quot` c) (replicate c ())
```
Then we can rebalance `xs` along it:
```haskell
xs' = zipWith template xs
```
Now `xs'` will be *full* of 2-3 trees of size `c`! All that remains is to use a backwards version of `mapMulFT`

**Comment by foxik** [comment] 2015-03-15 08:09
Closing as an incomplete duplicate of #145.

**Closed by foxik** 2015-03-15 08:09 UTC
