### ISSUE TITLE
performance of `Map.intersection`

### ISSUE THREAD

**Issue by amigalemming** [haskell/containers#177] opened 2016-01-18 16:54 UTC
The documentation of `Map.intersection` states that it requires runtime "O(n+m)". Wouldn't this be pretty slow? I hoped that `Map.intersection m (Map.singleton x)` would require only as much time as `Map.lookup x m`, i.e. "O(log n)". If `n>m`, then I could perform `m` lookups with costs `log n` and then build a new Map with `Map.fromList` requiring `m*log m` steps. In total I need `m*(log n+log m)`. That is, without the size assumptions I would expect a runtime like "min n m * (log n + log m)".
Same problem for `Map.isSubmapOf` and friends and corresponding `Set` functions.

**Comment by foxik** [comment] 2016-01-18 19:16
Well, for `n>=m` you can get `O(m log n)` -- the problem is that for `m ~ n` that is `O(n log n)`, which is higher than `O(n)`.

From the theoretical point of view, you can get `O(m log (n/m))` (see for example Hwang and Lin  1972 http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.419.8292), which has the best from both worlds -- it is `O(m log n)` for `m << n` and `O(m)` for `m ~ n`. Nevertheless, it has high constants and is not easy to implement.

However, when looking through the code, I believe the time complexities are just documented wrong. The `isSubmapOf` is definitely `O(first_map_size * log second_map_size)`, and I am not sure if the `O(m+n)` really holds. The same for `Map.intersect`, `Map.union` and `Map.mergeWithKey`: it is quite obvious that `O(first_map_size * log second_map_size)` holds (there is recursion on the first map, each step done in at most O(log second_map_size) time), while it is not obvious whether the `O(m+n)` does hold.

These comments with complexities are in the package for a long time -- I am not sure if someone remembers the claims for putting them there. Most obvious fix is probably to replace with them with complexities that we can prove.

Any ideas from your side?

**Comment by amigalemming** [comment] 2016-01-18 19:50
On Mon, 18 Jan 2016, Milan Straka wrote:

> Well, for n>=m you can get O(m log n) -- the problem is that for m ~ n that is O(n log n), which is higher than O(n).

Then O(min (m*log n) (n+m)) would give me a good idea of the performance.

> However, when looking through the code, I believe the time complexities are just documented wrong. The isSubmapOf is
> definitely O(first_map_size * log second_map_size), and I am not sure if the O(m+n) really holds. The same for
> Map.intersect, Map.union and Map.mergeWithKey: it is quite obvious that O(first_map_size * log second_map_size) holds
> (there is recursion on the first map, each step done in at most O(log second_map_size) time), while it is not obvious
> whether the O(m+n) does hold.

If the functions have a bias I would like to know. E.g. if 
Map.intersection is fast when the first map is small, then I would try to 
arrange the operands such that the first map is the expected smaller one.

**Comment by jwaldmann** [comment] 2016-02-10 15:42
I join this "improve documentation" request.

See also https://mail.haskell.org/pipermail/haskell-cafe/2016-February/123099.html (which I started in ignorance of the above discussion).

**Comment by jwaldmann** [comment] 2016-02-10 22:31
> ... fast when the first map is small, then ...

... I would expect that the library implementation (not the user) compares sizes of arguments, and re-orders if appropriate.

**Comment by foxik** [comment] 2016-02-11 07:22
Note that we cannot just swap the arguments -- `intersection` (and also `union`) is left-biased, so swapping arguments can produce different results. But we could of course have two implementations and choose the better one.

To see the effect of differently sized arguments, you can use benchmarks/SetOperations/bench-SetOperations-{Set,Map} benchmark. For `union`, performance seems better if the second argument is smaller, while for `intersection` it is the other way around (if first argument is smaller, performance is better).

**Comment by jwaldmann** [comment] 2016-02-11 11:05
> left-biased

yes, I was thinking of `intersectionWith` anyway.

**Comment by jwaldmann** [comment] 2016-09-04 09:22
This issue can be closed now? The new implementation has the exact bounds that I want https://hackage.haskell.org/package/containers-0.5.8.1/docs/Data-Map-Strict.html#g:9

This looks very good!

Although documentation could be improved slightly - the semantics of `m <= n` is not completely clear.
I hope it is "let m be the size of the smaller of the two maps". (Pedantically, it could be "let m be the size
of the first argument", and then "this bound is only valid if m <= n" holds.)

**Comment by treeowl** [comment] 2016-09-04 14:07
Yes, m is the smaller size. Propose a concise wording, eh?

**Comment by treeowl** [comment] 2016-09-04 14:08
Fixed by new implementation.

**Closed by treeowl** 2016-09-04 14:08 UTC
