### ISSUE TITLE
Please ensure containers does not warn for incomplete-uni-patterns

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell/containers#685] opened 2019-11-11 16:56 UTC
As per [this accepted GHC proposal](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0071-Wall-uni-patterns.rst), GHC will add `incomplete-uni-patterns` and `incomplete-record-updates` to `-Wall`.  Could you please ensure that the following files do not give any warnings for `incomplete-uni-patterns`, perhaps by setting the pragma below?  (A clean compile of containers is needed to build GHC.)

`{-# OPTIONS_GHC -Wno-incomplete-uni-patterns #-}`

* [ ] `Data/Sequence/Internal.hs`
* [ ] `Data/IntMap/Internal.hs`
* [ ] `Data/IntMap/Strict/Internal.hs`

**Comment by sjakobi** [comment] 2020-07-15 05:59
Related: #590

**Comment by sjakobi** [comment] 2020-07-15 23:19
Actually, this issue looks like a duplicate of #590. @tomjaguarpaw feel free to chime in there! :)

**Closed by sjakobi** 2020-07-15 23:19 UTC
